# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/#section=configuration for more details
#
version: 2
jobs:
  build_app:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Build app
          command: |
            if [[ "$CIRCLE_BRANCH" =~ ^release\/.*$ ]]; then 
              echo "$CIRCLE_BRANCH"
            fi
workflows:
  version: 2
  build_and_deploy_to_dev:
    jobs:
      - build_app:
          filters:
            branches:
              only:
                - /^release\/.*/
